version: '3.1'

services:

  nginx:
    container_name: yuchuan-homepage
    image: nginx:alpine
    restart: always
    links:
      - php
    ports:
      - 80:80
    volumes:
      - ./dist:/app
      - ./docker/nginx-conf:/etc/nginx/conf.d
      - ./docker/certs:/etc/nginx/certs
